apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql2-pod
  template:
    metadata:
      name: mysql2-pod
      labels:
        name: mysql2-pod
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.30
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "secretpassword"
            - name: MYSQL_DATABASE
              value: "payment"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql2
  labels:
    name: mysql2
spec:
  type: NodePort
  selector:
    name: mysql2-pod
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30010
